### ISSUE TITLE
jquery post로 한글을 보내면 에러가 발생하네요

### ISSUE THREAD

**Issue by mwmw7** [lhky78/toonsquare_ai_kobert#5]
Request URL: https://stage.toonsquare.co/proxy/ai/emotion_bert
Request Method: POST
Status Code: 500 INTERNAL SERVER ERROR
Remote Address: 49.247.198.110:443
Referrer Policy: no-referrer-when-downgrade
access-control-allow-origin: https://stage.toonsquare.co
Connection: keep-alive
Content-Length: 290
Content-Type: text/html; charset=utf-8
Date: Tue, 07 Apr 2020 06:45:01 GMT
Server: nginx/1.14.0 (Ubuntu)
vary: Origin
X-Powered-By: Express
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Content-Length: 33
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: _ga=GA1.2.1439063540.1581929429; ai_user=pELH4|2020-03-12T08:58:47.815Z; _gid=GA1.2.553212129.1586228137; language=kr; _gat_gtag_UA_116935747_1=1; ai_session=tSb66|1586238925397|1586241896758.235
Host: stage.toonsquare.co
Origin: https://stage.toonsquare.co
Referer: https://stage.toonsquare.co/ai/emotion/kor?tester
Request-Id: |br80e.8+G6Z
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36
X-Requested-With: XMLHttpRequest

**Comment by lhky78** [comment]
langCode 분류하는 방법으로 해결!!
